---
  AllCops:
    TargetRubyVersion: 2.4
  
  Style/FrozenStringLiteralComment:
    Enabled: false
  
  Metrics/MethodLength:
    Max: 20
  
  Metrics/AbcSize:
    Max: 20
  
  Lint/AssignmentInCondition:
    Enabled: false
  
  Metrics/BlockLength:
    Exclude:
      - 'gene_system.gemspec'
      - 'spec/**/*'
